rssagg:
  build: .
  restart: 'always'
  command: sleep 9999
  ports:
    - "4242:8080" # Can be accessed from port 4242
  links:
    - postgres

postgres:
   image: postgres
   restart: 'always'
   ports:
     - "5431:5432" # Can be accessed from port 5431
   volumes:
     - ./data:/var/lib/postgresql/data
   environment:
     POSTGRES_PASSWORD: 'rssagg'
     POSTGRES_USER: 'rssagg'
     POSTGRES_DB: 'rssagg'